stat_server/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings
from django.shortcuts import redirect

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

BASE_URL_RE = r"^" + settings.BASE_URL.lstrip("/")

handler500 = 'unifiedstatistics.views.error500'

urlpatterns = patterns('',
    # set language
    url(BASE_URL_RE + 'setlang/$', 'unifiedstatistics.views.set_language'),
    # include urls from the unifiedstatistics app
    url(BASE_URL_RE, include('unifiedstatistics.urls')),
    # Redirect to home page
    url(BASE_URL_RE+ '$', lambda request: redirect('unifiedstatistics.views.dashboard')),
    # OpenID URLs
    url(BASE_URL_RE + 'openid/', include('django_mojeid.urls')),
    
    # Django admin:
    url(BASE_URL_RE + 'admin/', include(admin.site.urls)),
    # media for test client
    url(BASE_URL_RE + 'media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': 'media'}),
)

unifiedstatistics/urls.py
from django.conf.urls import patterns, url
import views


urlpatterns = patterns('',
    url(r'^$', views.dashboard, name='dashboard'),

    url(r'^stats/$', views.all_statistics),
    url(r'^stats/(?P<stat_code_name>\w+)/$', views.statistics_page),
    url(r'^stats/(?P<stat_code_name>\w+)/json/data/$', views.json_data),
    url(r'^stats/(?P<stat_code_name>\w+)/json/slices/$', views.json_slices),
    url(r'^stats/(?P<stat_code_name>\w+)/json/series/$', views.json_series),
    url(r'^stats/(?P<stat_code_name>\w+)/csv/$', views.csv_data),
    
    url(r'^dashchart/(?P<ref_code_name>\w+)/json/data/$', views.dashchart_data),
    
    url(r'^reports/$', views.reports),
    url(r'^reports/(?P<report_code_name>\w+)/$', views.report_page, name='report-page'),
    url(r'^reports/(?P<report_code_name>\w+)/(?P<stat_code_name>\w+)/(?P<position>\d+)/json/data/$', views.json_data),
    
    url(r'^animation_test/$', views.animation_test),
    
    url(r'^logout/$', views.logout_view),
    url(r'^login/$', views.login_view),
    url(r'^access/$', views.set_access_view),

    #url(r'^crash/$', views.crash),
)

unifiedstatistics/models.py
# build-in modules
from datetime import datetime

# django imports
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import Group
from django.core.cache import cache
from django.db.models.query import QuerySet
from django.utils.crypto import get_random_string

# third party imports
from transmeta import TransMeta
from guardian.models import UserObjectPermissionBase
from guardian.models import GroupObjectPermissionBase
from guardian.shortcuts import get_perms, assign_perm, remove_perm 

# local imports
from common import Consts


class Report(models.Model):
    """
    Represents a report to be shown at the report page
    """
    __metaclass__ = TransMeta

    code_name = models.SlugField(unique=True)
    name = models.CharField(max_length=64)
    report_file = models.FileField(verbose_name=_("File"),
                                 upload_to="offline_reports",
                                 null=True, blank=True)
    
    class Meta:
        translate = ('name', 'report_file')
    
    def __unicode__(self):
        if self.name:
            return self.name
        return self.code_name

    def is_offline(self):
        if hasattr(self.report_file, 'size'):
            return True
        return False
    
    def has_localized_file(self):
        if self.report_file:
            name = None
            for lang_code, _lang_name in settings.LANGUAGES:
                loc_file = getattr(self, "report_file_"+lang_code)
                if name and loc_file.name != name:
                    return True
                name = loc_file.name
            return False
        return None
    
    def get_localized_files(self):
        files = []
        for lang_code, _lang_name in settings.LANGUAGES:
            loc_file = getattr(self, "report_file_"+lang_code)
            files.append((lang_code, loc_file))
        return files


class DashboardChart(models.Model):
    """
    Represents a chart to be shown at the dashboard
    """
    __metaclass__ = TransMeta

    code_name = models.SlugField(unique=True)
    name = models.CharField(max_length=64)
    statistics = models.ForeignKey("Statistics")
    position = models.IntegerField(default=0)
    params = models.OneToOneField("ChartParamSet")

    class Meta:
        verbose_name = _("Dashboard chart")
        verbose_name_plural = _("Dashboard chart")
        translate = ('name',)


class ChartParamSetManager(models.Manager):
    def get_by_natural_key(self, code_name):
        return self.get(code_name=code_name)


class ChartParamSet(models.Model):
    """
    Represents a reference to specific params for a chart
    """
    __metaclass__ = TransMeta
    objects = ChartParamSetManager()
        
    TIME_PROC_CHOICES = (
        (Consts.TIME_AGGREG_NONE, _("Normal")),
        (Consts.TIME_AGGREG_DIFF, _("Difference")),
        (Consts.TIME_AGGREG_DIFF_REL, _("Relative difference")),
        )
    
    TIME_AGGREG_CHOICES = (
        (),
        )
    
    DATA_SCALING_CHOICES = (
        (Consts.SCALE_NORMAL, _("Normal")),
        (Consts.SCALE_RELATIVE_100, _("Relative in %")),
        )
    
    CLIENT_DATA_SCALING_CHOICES = (
        (Consts.CLIENT_SCALE_NORMAL, _("Normal")),
        (Consts.CLIENT_SCALE_LOG, _("Logarithmic")),
        )
        
    code_name = models.SlugField(unique=True)
    ref_date = models.CharField(max_length=16, default="")
    date_range = models.CharField(max_length=16)
    time_processing = models.IntegerField(choices=TIME_PROC_CHOICES,
                                          default=Consts.TIME_AGGREG_NONE)
    time_sampling = models.CharField(max_length=16, default="")
    data_scaling = models.IntegerField(choices=DATA_SCALING_CHOICES,
                                       default=Consts.SCALE_NORMAL)
    client_data_scaling = models.IntegerField(choices=CLIENT_DATA_SCALING_CHOICES,
                                              default=Consts.CLIENT_SCALE_NORMAL)
    include_other = models.BooleanField(default=False,
                        help_text=_("Should 'other' be created when limiting "
                                    "the number of series"))
    series_limit = models.IntegerField(default=0)
    one_series = models.CharField(max_length=255, null=True)
    slicing_dim = models.IntegerField(null=True)
    slicing_value = models.CharField(max_length=255, null=True)
    slicing_dim_2 = models.IntegerField(null=True)
    slicing_value_2 = models.CharField(max_length=255, null=True)
    slicing_dim_3 = models.IntegerField(null=True)
    slicing_value_3 = models.CharField(max_length=255, null=True)
    display_as = models.CharField(max_length=16, null=True)
    relative_scale_base = models.IntegerField(null=True,
                                              help_text=_("When using relative scale, this determines "
                                                          "the dimension creating the base. Defaults to "
                                                          "null using as base current series dimension."))
    
    def natural_key(self):
        return self.code_name
        
    def get_data_request_params(self):
        # we import here to avoid circular import because data_request
        # imports models
        from data_request import DataRequest
        if self.time_processing == Consts.TIME_AGGREG_NONE:
            if self.time_sampling:
                time_processing = "i-" + self.time_sampling
            else:
                time_processing = DataRequest.DEFAULT_TIME_PROCESSING
        else:
            time_processing = self.time_processing
        # scaling is synthesized from two values
        if self.data_scaling == Consts.SCALE_NORMAL and \
           self.client_data_scaling == Consts.CLIENT_SCALE_LOG:
            data_scaling = "log"
        else:
            data_scaling = self.data_scaling
        display_as = self.display_as if self.display_as else DataRequest.DEFAULT_DISPLAY_AS
        
        params = {DataRequest.KEY_REF_DATE: self.ref_date,
                  DataRequest.KEY_DATE_RANGE: self.date_range,
                  DataRequest.KEY_TIME_PROCESSING: time_processing,
                  DataRequest.KEY_DATA_SCALING: data_scaling,
                  DataRequest.KEY_SERIES_SET: self.one_series,
                  DataRequest.KEY_SERIES_LIMIT: self.series_limit,
                  DataRequest.KEY_INCLUDE_OTHER: self.include_other,
                  DataRequest.KEY_SLICING_DIM: self.slicing_dim,
                  DataRequest.KEY_SLICING_VALUE: self.slicing_value,
                  DataRequest.KEY_SLICING_DIM_2: self.slicing_dim_2,
                  DataRequest.KEY_SLICING_VALUE_2: self.slicing_value_2,
                  DataRequest.KEY_SLICING_DIM_3: self.slicing_dim_3,
                  DataRequest.KEY_SLICING_VALUE_3: self.slicing_value_3,
                  DataRequest.KEY_DISPLAY_AS: display_as,
                  DataRequest.KEY_RELATIVE_SCALE_BASE: self.relative_scale_base
                  }
        return params
    

class StatGroup(models.Model):
    """
    Represents a group of statistics
    """
    __metaclass__ = TransMeta
        
    code_name = models.SlugField(unique=True)
    name = models.CharField(max_length=64)
    statistics = models.ManyToManyField("Statistics",
                                        through="StatGroupToStatistics")
    position = models.PositiveIntegerField()
    info = models.TextField()
    
    class Meta:
        verbose_name = _("Statistics group")
        verbose_name_plural = _("Statistics group")
        translate = ('name', 'info')
        ordering = ("position",)
        
    def get_statistics(self):
        return self.statistics.order_by('statgrouptostatistics__position')
                

class ReportGroup(models.Model):
    """
    Represents a group of reports
    """
    __metaclass__ = TransMeta
        
    code_name = models.SlugField(unique=True)
    name = models.CharField(max_length=64)
    reports = models.ManyToManyField("Report",
                                        through="ReportGroupToReport")
    position = models.PositiveIntegerField()
    info = models.TextField()
    
    class Meta:
        verbose_name = _("Report group")
        verbose_name_plural = _("Report group")
        translate = ('name',)
        ordering = ("position",)
        
    def get_reports(self):
        return self.reports.order_by('reportgrouptoreport__position')


class ReportGroupToReport(models.Model):
    """
    Mapping between ReportGroup and Report providing an extra position
    attribute
    """
    report_group = models.ForeignKey(ReportGroup)
    report = models.ForeignKey('Report')
    position = models.PositiveSmallIntegerField()
    
    class Meta:
        unique_together = (("report_group", "report", "position"),)
        verbose_name = _("ReportGroup to Report mapping")
        verbose_name_plural = _("ReportGroup to Report mappings")
        ordering = ("position",)


class StatGroupToStatistics(models.Model):
    """
    Mapping between StatGroup and Statistics providing an extra position
    attribute
    """
    stat_group = models.ForeignKey(StatGroup)
    statistics = models.ForeignKey('Statistics')
    position = models.PositiveSmallIntegerField()
    
    class Meta:
        unique_together = (("stat_group", "statistics", "position"),)
        verbose_name = _("StatGroup to Statistics mapping")
        verbose_name_plural = _("StatGroup to Statistics mappings")
        ordering = ("position",)


class ReportSection(models.Model):
    """
    Represents a section of report
    """
    __metaclass__ = TransMeta
        
    name = models.CharField(max_length=64)
    report = models.ForeignKey(Report)
    position = models.PositiveSmallIntegerField()
    
    class Meta:
        unique_together = (("report", "position"),)
        verbose_name = _("Report section")

unifiedstatistics/templates/access.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block menu %}
{% include "tabs.html" with active_tab="stats" %}
{% endblock %}

{% block subtitle %}{% trans "Private area" %}{% endblock %}

{% block main_content %}

<div id="accordion">
{% include "login_box.html" %}

{% for group_rec in stat_groups %}
<h3>{{ group_rec.group.name|safe }}</h3>
    <ul>
    {% for stat in group_rec.stats %}
        <li><a href="{% url 'unifiedstatistics.views.statistics_page' stat.code_name %}">{{ stat.name|safe }}</a>{% if not stat.get_public %}&nbsp;<img src="{% static 'img/unlocked.png' %}" title="{% trans "Private statistics" %}" />{% endif %}</li>
    {% endfor %}
    </ul>
{% endfor %}
</div>

<div id="chart_frame_wrapper">

<h2>{% trans "Set access" %}</h2>

{% if submitted %}
    {% if key_valid %}
        {% if added %}
        <p>{% trans "You entered valid access key and gained access to following statistics:" %}</p>
        <ul>
        {% for stat in new_stats %}
            <li>{{ stat }}</li>
        {% endfor %}
        </ul><br>
        {% else %}
        <p>{% trans "You have already access to all statistics connected with given key." %}</p>
        {% endif %}
    {% else %}
    <p>{% trans "You entered invalid access key." %}</p>
    {% endif %}
{% else %}
<p>
{% blocktrans %}
Hello, welcome to your private area. To have access to private graphs, please enter private key you received.
If you do not have one and still think you should have access, please contact site administrator.
{% endblocktrans %}
</p>
{% endif %}

<form method="post">
    {% csrf_token %}
    <input type="text" name="key" placeholder="{% trans "Your access key" %}">
    <button type="submit">{% trans "Submit" %}</button>
</form>

</div>

<div class="clear-fix"></div>

{% endblock %}

unifiedstatistics/templates/all_statistics.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block menu %}
{% include "tabs.html" with active_tab="stats" %}
{% endblock %}

{% block subtitle %}{% trans "Available statistics" %}{% endblock %}

{% block main_content %}

<div id="accordion">
{% include "login_box.html" %}

{% for group_rec in stat_groups %}
<h3>{{ group_rec.group.name|safe }}</h3>
    <ul>
    {% for stat in group_rec.stats %}
        <li><a href="{% url 'unifiedstatistics.views.statistics_page' stat.code_name %}">{{ stat.name|safe }}</a>{% if not stat.get_public %}&nbsp;<img src="{% static 'img/unlocked.png' %}" title="{% trans "Private statistics" %}" />{% endif %}</li>
    {% endfor %}
    </ul>
{% endfor %}
</div>

<div id="chart_frame_wrapper">
<h2>{% trans "About .cz statistics" %}</h2>

<p>
{% blocktrans %}
This website contains a compilation of statistical data published by CZ.NIC, z.s.p.o., the
.cz domain registry.
{% endblocktrans %}
</p>
<p>
{% blocktrans %}
The statistics are divided into several categories and may be easily navigated
using the menu on the left side of this page.
{% endblocktrans %}
</p>

<h2>{% trans "Note" %}</h2>


<p>
{% blocktrans %}
JavaScript is necessary to view the charts displayed on this website.
If you do not have JavaScript turned on in your browser, you will not be able to
see the presented statistical data.
{% endblocktrans %}
</p>


<h2>{% trans "Used technologies" %}</h2>

<p>
{% blocktrans %}
The charts displayed on these pages are rendered by the <a href="http://www.highcharts.com/">Highcharts library</a> using the <a href="https://gitlab.labs.nic.cz/labs/ogra">OGRA adaptor library</a>. 
{% endblocktrans %}
</p>


</div>

<div class="clear-fix"></div>

{% endblock %}

unifiedstatistics/templates/animation_test.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="copyright" content="CZ.NIC, zájmové sdružení právnických osob" />  
    <meta lang="en" name="description" content="CZ.NIC Statistics" />    
    
    
    <title>DNSSEC by registrators - cz. statistics</title>
    <link rel="shortcut icon" type="image/x-icon" href="/stats/static/img/favicon.ico" />
    
    <!-- link type="text/css" rel="stylesheet" media="all" href="/stats/static/css/style.css" /-->
    
<script type="text/javascript"
    src="https://www.google.com/jsapi"></script>

<script type="text/javascript" 
    src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<script type="text/javascript" src="/stats/static/js/bindfix.js"></script>
<script type="text/javascript" src="/stats/static/js/chart.js"></script>
<script type="text/javascript" src="/stats/static/js/stats.js"></script>
<script type="text/javascript" src="/stats/static/js/ui.dropdownchecklist-1.4-min.js"></script>

<script type="text/javascript">
    google.load("visualization", "1",
    		{packages:["corechart","table"],
    	     language: 'en'});
 
    error = false;
	update_chart = function(chart, response){
		var data = null;
	    eval('data =' + response.data);
	    if (response.ok && data != null) {
	        var title = response.chart_title;
	        var datatable = new google.visualization.DataTable(data, 0.6);
	        var vaxis_params = {title: response.dimension_y};
	        //vaxis_params.logScale = true;
	        vaxis_params.format = "#";
	        var haxis_params = {title: response.dimension_x};
	        /* sort accorting to column 1 if data is not time dependent */
	        if (!response.has_time) {
	            datatable.sort([{column: 1, desc: true}]);
	        } 
	        var params = {
                   width: 800,
                   height: 600,
                   title: title,
                   isStacked: response.summable_series,
                   vAxis: vaxis_params,
                   hAxis: haxis_params,
                   animation:{
                       duration: 400,
                       easing: 'out'
                     },
               }
            chart.draw(datatable, params);
	    }
	}
	
	show_chart_for_url = function (chart, url) {
	    jQuery.ajax({
	        dataType: "json",
	        url: url,
	        success: function(response) { update_chart(chart, response); },
	        error: function(jqXHR, textStatus, errorThrown) {
	        	error = true;
	        	console.log("ERROR: ", textStatus, errorThrown);
	        	}
	    });
	}   
	
	next_step = function(chart) {
		if (start < end && !error) {
			var date_str = start.toISOString().substring(0, 10);
			$("#chart_title").html(date_str);
			var url = data_url_base + date_str;
			show_chart_for_url(chart, url);
			start.setTime(start.getTime() + 20*24*60*60*1000);
			setTimeout(function() { next_step(chart) }, 800);
		}
	}
	
	function stop() {
		error = true;
	}

    var start = new Date(2009, 0, 1, 0, 0, 0, 0);
    var data_url_base = "{% url 'unifiedstatistics.views.json_data' 'dnssec_by_registrator' %}?sd=dnssec_status&sv=162&dr=0d&tp=i-1d&ss=0&ds=normal&da=chart&rd=";
	var end = new Date(2012, 10, 30, 0, 0, 0, 0);
	
    $(document).ready(function() {
	    //console.log(start, end);
    	var chart_div = document.getElementById("chart_div");
    	var chart = new google.visualization.ColumnChart(chart_div);
		next_step(chart);
	});
</script>

  </head>
  
  
<body>

<div id="chart_frame_wrapper">
<h2>DNSSEC by registrators</h2>


<h3 id="chart_title"></h3>
<button onclick="javascript:stop()">Stop</button>
<div id="chart_div"></div>
</div>


  </body>
</html>

unifiedstatistics/templates/dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block menu %}
{% include "tabs.html" with active_tab="dashboard" %}
{% endblock %}

{% block subtitle %}{% trans "Dashboard" %}{% endblock %}

{% block special_head %}
<script type="text/javascript"
    src="//www.google.com/jsapi"></script>
    
<script type="text/javascript" 
    src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

<script type="text/javascript" src="{% static 'js/highcharts3/highcharts.js' %}"></script>

<script type="text/javascript" src="{% static 'js/ogra/ogra.js' %}"></script>
<script type="text/javascript" src="{% static 'js/chart.js' %}"></script>

<script type="text/javascript">
    google.load("visualization", "1",
    		{packages:["corechart","table"], language: '{{ LANGUAGE_CODE }}'});
    $(document).ready(function() {
    	//$("#menu").menu();
    	var width = $("#dashboard_wrapper").innerWidth();
		width = Math.max(460, width);
    	var chart_width = Math.floor(width / Math.floor(width/460)) - 10;
        {% for chart_ref in chart_refs %}
        var dash = document.getElementById("chartref-{{ chart_ref.code_name }}");
        var pack = new ChartPackage(dash, dash, null, chart_width, Math.floor(chart_width/1.418), '{{ LANGUAGE_CODE }}', undefined);
        pack.show_chart('{% url 'unifiedstatistics.views.dashchart_data' chart_ref.code_name %}?lang={{ LANGUAGE_CODE }}');
        {% endfor %}        
    });
</script>
{% endblock %}


{% block main_content %}
{#<h2>{% trans "Dashboard" %}</h2>#}

<div id="dashboard_wrapper">
    {% for chart_ref in chart_refs %}
    <div id="chartref-{{ chart_ref.code_name }}" class="dash_chart"></div>
    {% endfor %}
</div>

<div class="clear-fix"></div>

{% endblock %}

unifiedstatistics/templates/login_box.html
{% load i18n %}
{% load staticfiles %}

{% if user.is_authenticated %}
<div id="login_box">
  {% trans "Logged in as:" %}<br />
  <b>{{ user.get_full_name }}</b><br />
  <a href="{% url 'unifiedstatistics.views.set_access_view' %}">{% trans "Set access" %}</a><br />
  <a href="{% url 'unifiedstatistics.views.logout_view' %}">{% trans "Logout" %}</a>
</div>
{% endif %}

unifiedstatistics/templates/report_page.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load markup %}

{% block menu %}
{% include "tabs.html" with active_tab="reports" %}
{% endblock %}

{% block subtitle %}{{ report.name|safe }}{% endblock %}

{% block breadcrumbs %}{% trans "Report" %} &gt; {{ report.name|striptags }}{% endblock %}

{% block special_head %}
<script type="text/javascript"
    src="//www.google.com/jsapi"></script>

<script type="text/javascript" 
    src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script type="text/javascript" 
    src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

{% if LANGUAGE_CODE == "cs" %}
<script type="text/javascript" 
    src="{% static 'js/ui.datepicker-cs.js' %}"></script>
{% endif %}

<script type="text/javascript" src="{% static 'js/bindfix.js' %}"></script>


<script type="text/javascript" src="{% static 'js/highcharts3/highcharts.js' %}"></script>
<script type="text/javascript" src="{% static 'js/highcharts3/modules/exporting.js' %}"></script>

<script type="text/javascript" src="{% static 'js/ogra/ogra.js' %}"></script>

<script type="text/javascript" src="{% static 'js/chart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/reports.js' %}"></script>
<link rel="stylesheet"
    href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" />

<script type="text/javascript">
    google.load("visualization", "1",
            {packages:["corechart","table"],
             language: '{{ LANGUAGE_CODE }}'});

    $(document).ready(function() {
        chart_packages = new Array();
        {% for rel in report.reporttostatistics_set.all %}
        setup_chart("{{ rel.statistics.code_name }}", {{rel.position}}, '{{ LANGUAGE_CODE }}');
        {% endfor %}
    });
</script>

{% endblock %}


{% block main_content %}

<div id="accordion">
{% for group_rec in report_groups %}
    {% if group_rec.group.code_name == 'online' %}
        {% for rep in group_rec.reports %}
            {% if rep.code_name == report.code_name %}
                <h3 id="toc"><strong>{{ rep.name|safe }}</strong></h3>
                {% for sec in report.reportsection_set.all %}
                    <h4>{{ sec.name|safe }}</h4>
                    <ul>
                    {% for rel in sec.reporttostatistics_set.all %}
                        <li><a href="#{{rel.position}}">{{ rel.real_name|safe }}</a></li>
                    {% endfor %}
                    </ul>
                {% empty %}
                    <ul>
                    {% for rel in report.reporttostatistics_set.all %}
                        <li><a href="#{{rel.position}}">{{ rel.real_name|safe }}</a></li>
                    {% endfor %}
                    </ul>
                {% endfor %}
            {% else %}
                <h3><a href="{% url 'unifiedstatistics.views.report_page' rep.code_name %}">{{ rep.name|safe }}</a></h3>
            {% endif %}
        {% endfor %}
    {% else %}
        <h3>{{ group_rec.group.name|safe }}</h3>
        <ul>
        {% for rep in group_rec.reports %}
            {% if rep.code_name == report.code_name %}
                <li id="toc"><strong>{{ rep.name|safe }}</strong>
                    {% for sec in report.reportsection_set.all %}
                        <h4>{{ sec.name|safe }}</h4>
                        <ul>
                        {% for rel in sec.reporttostatistics_set.all %}
                            <li><a href="#{{rel.position}}">{{ rel.real_name|safe }}</a></li>
                        {% endfor %}
                        </ul>
                    {% empty %}
                        <ul>
                        {% for rel in report.reporttostatistics_set.all %}
                            <li><a href="#{{rel.position}}">{{ rel.real_name|safe }}</a></li>
                        {% endfor %}
                        </ul>
                    {% endfor %}
                </li>
            {% else %}
                <li><a href="{% url 'unifiedstatistics.views.report_page' rep.code_name %}">{{ rep.name|safe }}</a></li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endif %}
{% endfor %}
</div>
<a href="#toc" class="toc">{% trans "^ To the Table of Contents" %}</a>


<div id="chart_frame_wrapper">
<h2>{{ report.name|safe }}</h2>

{% for rel in report.reporttostatistics_set.all %}
<span id="{{ rel.position }}"></span>
<div id="chart_wrapper_{{ rel.position }}" class="chart_wrapper report">
    <div id="json_info_{{ rel.position }}" class="json_info"></div>
    
    <h3 id="chart_title_{{ rel.position }}" class="chart_title"></h3>
    <div id="chart_div_{{ rel.position }}" class="chart_div"></div>
    <div class="clear-fix"></div>
    {% if rel.highlight %}
    <p class="chart_info" id="chart_info_{{ rel.position }}">{{ rel.highlight|safe }}</p>
    {% endif %}
    {% if rel.info %}
    {{ rel.info|markdown:"safe" }}
    {% elif rel.statistics.info %}
    {{ rel.statistics.info|markdown:"safe" }}
    {% endif %}
</div>
{% endfor %}

</div>

<div class="clear-fix"></div>
{% endblock %}

unifiedstatistics/templates/tabs.html
{% load i18n %}
            <ul id="nav2">

                <li class="nav-mnu1{% if active_tab == 'dashboard'%} active{% endif %}">
                    <a href="{% url 'unifiedstatistics.views.dashboard' %}">{% trans "Dashboard" %}</a>
                </li>

                <li class="nav-mnu2{% if active_tab == 'stats'%} active{% endif %}">
                    <a href="{% url 'unifiedstatistics.views.all_statistics' %}">{% trans "Statistics" %}</a>
                </li>

                <li class="nav-mnu3{% if active_tab == 'reports'%} active{% endif %}">
                    <a href="{% url 'unifiedstatistics.views.reports' %}">{% trans "Reports" %}</a>
                </li>

            </ul>